### ISSUE TITLE
Create Queue_DataStructure implementation in C++

### ISSUE THREAD

**Issue by subhahu123** [Yet-Another-Series/Yet_Another_Algorithms_Repository#105]
* Please follow the [Contributing Guidelines](https://github.com/AshishOhri/Yet_Another_Algorithms_Repository/blob/master/CONTRIBUTING.md) & naming conventions in the guidelines accordingly. 🙂
* Following naming guidelines is important to maintain consistency.😊
* Please *NOTE*: In case, same implementation of an algorithm is submitted by someone else and it gets accepted, then your contribution won't be merged ( to avoid duplicates )

**Comment by luabras** [comment]
I already created a pull request submitting an implementation of queues and stacks in c ++

**Comment by Preethirkrish** [comment]
i would like to help out

**Comment by anujji1999** [comment]
Should i take this issue?

**Comment by ivinayaks** [comment]
Can I take this up? The issue seems to be listed as open.

**Comment by AshishOhri** [comment]
Sorry this issue has been solved.
