### ISSUE TITLE
Create Heap_Sort_Algo implementation in C

### ISSUE THREAD

**Issue by Sarvesh18** [Yet-Another-Series/Yet_Another_Algorithms_Repository#130]
* Please follow the [Contributing Guidelines](https://github.com/AshishOhri/Yet_Another_Algorithms_Repository/blob/master/CONTRIBUTING.md) & naming conventions in the guidelines accordingly. 🙂
* Following naming guidelines is important to maintain consistency.😊
* Please *NOTE*: In case, same implementation of an algorithm is submitted by someone else and it gets accepted, then your contribution won't be merged ( to avoid duplicates )

**Comment by petrmanek** [comment]
Hi, what's the state of this issue. Is it still "up for grabs"? If so, can I do it?

**Comment by andrecoco** [comment]
Hi, can i do it?

**Comment by petrmanek** [comment]
@andrecoco Go for it if you want! I'm currently working on other stuffs.

**Comment by dingM-GZh** [comment]
I just wrote one in C

**Comment by Richardson-Rayshorn** [comment]
Is this still up for grabs?
