### ISSUE TITLE
Create Kadane's Algorithm in Python.

### ISSUE THREAD

**Issue by BakedScorpion** [Yet-Another-Series/Yet_Another_Algorithms_Repository#139]
* Please follow the [Contributing Guidelines](https://github.com/AshishOhri/Yet_Another_Algorithms_Repository/blob/master/CONTRIBUTING.md) & naming conventions in the guidelines accordingly. 🙂
* Following naming guidelines is important to maintain consistency.😊
* Please *NOTE*: In case, same implementation of an algorithm is submitted by someone else and it gets accepted, then your contribution won't be merged ( to avoid duplicates )

**Comment by aadarsh18** [comment]
[kadane algorithm.pdf](https://github.com/Yet-Another-Series/Yet_Another_Algorithms_Repository/files/3734203/kadane.algorithm.pdf)
Kadane Algorithm in Python
