### ISSUE TITLE
Add Knapsack Algorithm 0/1 in C++

### ISSUE THREAD

**Issue by BakedScorpion** [Yet-Another-Series/Yet_Another_Algorithms_Repository#141]
* Please follow the [Contributing Guidelines](https://github.com/AshishOhri/Yet_Another_Algorithms_Repository/blob/master/CONTRIBUTING.md) & naming conventions in the guidelines accordingly. 🙂
* Following naming guidelines is important to maintain consistency.😊
* Please *NOTE*: In case, same implementation of an algorithm is submitted by someone else and it gets accepted, then your contribution won't be merged ( to avoid duplicates )

**Comment by prakharvk** [comment]
I am working on it

**Comment by BakedScorpion** [comment]
@prakharvk  I have already submitted a PR. Please check for other issues or open one. 
Thanks!

**Comment by prakharvk** [comment]
> @prakharvk I have already submitted a PR. Please check for other issues or open one.
> Thanks!

Oh sorry I didn't see that, I have already made a PR for it now.

**Comment by BakedScorpion** [comment]
@prakharvk This will cause conflict. It would be great if you could add a solution in some other language say python.
