### ISSUE TITLE
Create Segment Tree Implementation for XOR Range Query

### ISSUE THREAD

**Issue by Anish-Jain-AJ** [Yet-Another-Series/Yet_Another_Algorithms_Repository#196]
* Please follow the [Contributing Guidelines](https://github.com/AshishOhri/Yet_Another_Algorithms_Repository/blob/master/CONTRIBUTING.md) & naming conventions in the guidelines accordingly. 🙂
* Following naming guidelines is important to maintain consistency.😊
* Please *NOTE*: In case, same implementation of an algorithm is submitted by someone else and it gets accepted, then your contribution won't be merged ( to avoid duplicates )

**Comment by blinker7** [comment]
Is an update query also required?

**Comment by Anish-Jain-AJ** [comment]
It can be added

**Comment by Anish-Jain-AJ** [comment]
Update Query Function Added.
@blinker7
