### ISSUE TITLE
Create bubble_sort implementation in C

### ISSUE THREAD

**Issue by iam-Shashank** [Yet-Another-Series/Yet_Another_Algorithms_Repository#31]
* Please follow the [Contributing Guidelines](https://github.com/AshishOhri/Yet_Another_Algorithms_Repository/blob/master/CONTRIBUTING.md) & naming conventions in the guidelines accordingly. 🙂
* Following naming guidelines is important to maintain consistency.😊
* Please **NOTE**: In case, same implementation of an algorithm is submitted by someone else and it gets accepted, then your contribution won't be merged ( to avoid duplicates )

**Comment by aman05382** [comment]
I am ready to do please assign me

**Comment by aman05382** [comment]
Don't get me wrong but I am a newbie here that's why many problems occur please understand, but after many attempts I successfully done my PR. please review it
