### ISSUE TITLE
Create binary_search implementation in java

### ISSUE THREAD

**Issue by AshishOhri** [Yet-Another-Series/Yet_Another_Algorithms_Repository#48]
* Please follow the [Contributing Guidelines](https://github.com/AshishOhri/Yet_Another_Algorithms_Repository/blob/master/CONTRIBUTING.md) & naming conventions in the guidelines accordingly. 🙂
* Following naming guidelines is important to maintain consistency.😊
* Please *NOTE*: In case, same implementation of an algorithm is submitted by someone else and it gets accepted, then your contribution won't be merged ( to avoid duplicates )

**Comment by manuelcoppotelli** [comment]
I'll do this one
