### ISSUE TITLE
Create binary_search implementation in C++

### ISSUE THREAD

**Issue by AshishOhri** [Yet-Another-Series/Yet_Another_Algorithms_Repository#49]
* Please follow the [Contributing Guidelines](https://github.com/AshishOhri/Yet_Another_Algorithms_Repository/blob/master/CONTRIBUTING.md) & naming conventions in the guidelines accordingly. 🙂
* Following naming guidelines is important to maintain consistency.😊
* Please *NOTE*: In case, same implementation of an algorithm is submitted by someone else and it gets accepted, then your contribution won't be merged ( to avoid duplicates )

**Comment by manuelcoppotelli** [comment]
I'll do this one

**Comment by Joelfmjr** [comment]
Can I also do this one?

**Comment by NanuSai** [comment]
I'll try this one!

**Comment by Nishanth-S1142001** [comment]
I will do this

**Comment by Preethirkrish** [comment]
i would like to do binary search in c++.

**Comment by anujji1999** [comment]
Is anyone working on this?

**Comment by omega07** [comment]
> Is anyone working on this?

yes i have made a pull request

**Comment by rishi255** [comment]
Can I do this?
