### ISSUE TITLE
Create Kadane_Algorithim implementation in C

### ISSUE THREAD

**Issue by subhahu123** [Yet-Another-Series/Yet_Another_Algorithms_Repository#73]
* Please follow the [Contributing Guidelines](https://github.com/AshishOhri/Yet_Another_Algorithms_Repository/blob/master/CONTRIBUTING.md) & naming conventions in the guidelines accordingly. 🙂
* Following naming guidelines is important to maintain consistency.😊
* Please *NOTE*: In case, same implementation of an algorithm is submitted by someone else and it gets accepted, then your contribution won't be merged ( to avoid duplicates )

**Comment by BakedScorpion** [comment]
@subhahu123  I will open a PR for this!

**Comment by aadarsh18** [comment]
[kadane algo...pdf](https://github.com/Yet-Another-Series/Yet_Another_Algorithms_Repository/files/3734173/kadane.algo.pdf)
Kadane Algorithm in C++
