### ISSUE TITLE
Create Kadane_Algorithim implementation in C++

### ISSUE THREAD

**Issue by subhahu123** [Yet-Another-Series/Yet_Another_Algorithms_Repository#74]
* Please follow the [Contributing Guidelines](https://github.com/AshishOhri/Yet_Another_Algorithms_Repository/blob/master/CONTRIBUTING.md) & naming conventions in the guidelines accordingly. 🙂
* Following naming guidelines is important to maintain consistency.😊
* Please *NOTE*: In case, same implementation of an algorithm is submitted by someone else and it gets accepted, then your contribution won't be merged ( to avoid duplicates )

**Comment by adinalini** [comment]
I would love to take this up

**Comment by blinker7** [comment]
I can do this too

**Comment by ranaakash** [comment]
@subhahu123 this isssue is still  pending ?

**Comment by subhahu123** [comment]
@ranaakash  yes

**Comment by anujji1999** [comment]
Is anyone working on this issue?

**Comment by RAJKUMARRZ** [comment]
I would like to work on it.

**Comment by Richardson-Rayshorn** [comment]
Is it still available?

**Comment by AshishOhri** [comment]
Sorry, it is already resolved. Thanks anyways!
