### ISSUE TITLE
Create Shell_Sort implementation in C++

### ISSUE THREAD

**Issue by subhahu123** [Yet-Another-Series/Yet_Another_Algorithms_Repository#81]
* Please follow the [Contributing Guidelines](https://github.com/AshishOhri/Yet_Another_Algorithms_Repository/blob/master/CONTRIBUTING.md) & naming conventions in the guidelines accordingly. 🙂
* Following naming guidelines is important to maintain consistency.😊
* Please *NOTE*: In case, same implementation of an algorithm is submitted by someone else and it gets accepted, then your contribution won't be merged ( to avoid duplicates )

**Comment by petrmanek** [comment]
Hi, I can do this.

**Comment by blinker7** [comment]
Hi, can I work on this too?

**Comment by petrmanek** [comment]
@blinker7 Sadly, I'm almost ready to submit PR. If you're going to do this, you'll be duplicating my work.

**Comment by petrmanek** [comment]
Here's an idea: @blinker7, if you still want to do this, I can submit my work and you can then work to improve it. For instance, there are quite a few gap sequences that can be used with ShellSort. Perhaps you'll be able to find one that is better than mine (a very basic one).

**Comment by blinker7** [comment]
@petrmanek okay! I can try that.

**Comment by petrmanek** [comment]
Alright. Took me longer than expected, but here it is -- shell_sort in C++.

@blinker7 Feel free to have fun with gap sequences!
