### ISSUE TITLE
Create Merge_Sort_Algo implementation in Javascript

### ISSUE THREAD

**Issue by subhahu123** [Yet-Another-Series/Yet_Another_Algorithms_Repository#92]
* Please follow the [Contributing Guidelines](https://github.com/AshishOhri/Yet_Another_Algorithms_Repository/blob/master/CONTRIBUTING.md) & naming conventions in the guidelines accordingly. 🙂
* Following naming guidelines is important to maintain consistency.😊
* Please *NOTE*: In case, same implementation of an algorithm is submitted by someone else and it gets accepted, then your contribution won't be merged ( to avoid duplicates )

**Comment by stackyism** [comment]
@subhahu123 Can I take this up?

**Comment by subhahu123** [comment]
> @subhahu123 Can I take this up?

yes

**Comment by stackyism** [comment]
@subhahu123 Queries.
- should the code be accepting the number of entries & then the entries themselves from user?
   - if yes
      - should I assume it is going to run in browser & accept input using prompt ?
      - or should I assume it is going to run using node & accept input by waiting on user input by blocking thread ?
    - if no
       - then should I just take dummy values & console log or just export the mergeSort function?

**Comment by stackyism** [comment]
Hi @subhahu123 
Please have a look at PR #167 . 
Thank You! :)
